# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            prestochango
tagline:          'A library for working with CITE Collections'
description:      'prestochango is a JVM library for working with CITE Collections'
baseurl: '/prestochango/'


author:
  name:           'Neel Smith'
 

paginate:         5

github:
  repo:           https://github.com/neelsmith/cite

version:          0.12.0

links:
  - title: Github project
    url: https://github.com/cite-architecture/prestochango
    external: true
  - title: CITE architecture home page
    url: http://cite-architecture.github.io/
    external: true
   